# Tensorflow

TensorFlow is a free and open-source software library for dataflow and differentiable programming across a range of tasks. It is a symbolic math library, and is also used for machine learning applications such as neural networks.

It is used for both research and production at Google.‍

TensorFlow was developed by the Google Brain team for internal Google use. It was released under the Apache License 2.0 on November 9, 2015

TensorFlow is inevitably the package to use for Deep Learning, if you are doing any sort of business. 

Keras is the standard API in TensorFlow and the easiest way to implement neural networks. Deployment is much easier, compared to PyTorch – so unless you are doing research, TensorFlow is most likely the way to go. 

In [ ]:
#%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

# Common Use Operations

Let me introduce the bread and butter of TensorFlow, the most commonly used operations. We are going to take a look at the following

### Making tensors with **tf.constant** and **tf.Variable**
### Concatenation of two tensors with **tf.concat**
### Making tensors with **tf.zeros** or **tf.ones**
### Reshaping data with **tf.reshape**
### Casting tensors to other data types with **tf.cast**

### How to make tensors with tf.contant and tf.Variable

Perhaps one of the simplest operations in tensorflow is making a constant or variable. You simply call the tf.constant or tf.Variable function and specify an array of arrays.

In [ ]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

print(A)

tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)


In [ ]:
# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])
print(VA)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 2],
       [5, 2]], dtype=int32)>


In [ ]:
# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])
print(B)

tf.Tensor(
[[9 5]
 [1 3]], shape=(2, 2), dtype=int32)


In [ ]:
# In Tensorflow 1.x - for lazy execution (delayed execution)
'''
# Turn off when running TF 2
with tf.Session() as sess:
  res = sess.run(B)
  print(res)
'''

'\n# Turn off when running TF 2\nwith tf.Session() as sess:\n  res = sess.run(B)\n  print(res)\n'

## How to concatenate two tensors with tf.concat

Let's say that we have two tensors, perhaps it could be two observations. We want to concat the two tensors A and B into a single variable in Python – how do we do it?

We simply use the tf.concat, and specify the values and axis.

In [ ]:
# Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
                 [5, 2]])

# Making another tensor B
B = tf.constant([[9, 5],
                 [1, 3]])

# Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
#print(('Adding B\'s columns to A:\n{0}').format(AB_concatenated.numpy()))
print(('Adding B\'s columns to A:\n{0}').format(AB_concatenated))

# Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
#print(('\nAdding B\'s rows to A:\n{0}').format(AB_concatenated.numpy()))
print(('Adding B\'s columns to A:\n{0}').format(AB_concatenated))


Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]
Adding B's columns to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [ ]:
'''
# Turn off when running TF 2
with tf.Session() as sess:
  res = sess.run(AB_concatenated)
  print(res)
'''

'\n# Turn off when running TF 2\nwith tf.Session() as sess:\n  res = sess.run(AB_concatenated)\n  print(res)\n'

In [ ]:
# Making a Variable tensor VA, which can change. Notice it's .Variable
VA = tf.Variable([[3, 2],
                 [5, 2]])

# Concatenate columns of a constant and a variable
AB_concatenated = tf.concat(values=[VA, B], axis=1)
#print(('Adding B\'s columns to VA:\n{0}').format(AB_concatenated.numpy()))
print(('Adding B\'s columns to A:\n{0}').format(AB_concatenated))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]


## How to make tensors with tf.zeros and tf.ones

Creating tensors with just tf.constant and tf.Variable can be tedious if you want to create big tensors. Imagine you want to create random noise – well, you could do that by making a tensor with tf.zeros or tf.ones.

In [ ]:
# Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
#print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(tensor.numpy()))
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(tensor))

# Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
#print(('\nTensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(tensor.numpy()))
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(tensor))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Tensor full of zeros as int32, 3 rows and 4 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## How to reshape data with tf.reshape

We might have generated some random noise or have a dataset of images in different sizes, which needs to be one-dimensional in order to fit into some filter or convolution.

We could use tf.reshape to reshape the images in whichever way we want. 

All we do here is define a tensor, and then reshape it into 8 columns with 1 row, instead of 2 columns with 4 rows.

In [ ]:
# Making a tensor for reshaping
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor, shape = [1, 8])

#print(('Tensor BEFORE reshape:\n{0}').format(tensor.numpy()))
print(('Tensor BEFORE reshape:\n{0}').format(tensor))

#print(('\nTensor AFTER reshape:\n{0}').format(reshaped_tensor.numpy()))
print(('\nTensor AFTER reshape:\n{0}').format(reshaped_tensor))


Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2 9 5 1 3]]


In [ ]:
# Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor, shape = [2, 4])

#print(('Tensor BEFORE reshape:\n{0}').format(tensor.numpy()))
print(('Tensor BEFORE reshape:\n{0}').format(tensor))
#print(('\nTensor AFTER reshape:\n{0}').format(reshaped_tensor.numpy()))
print(('\nTensor AFTER reshape:\n{0}').format(reshaped_tensor))

Tensor BEFORE reshape:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor AFTER reshape:
[[3 2 5 2]
 [9 5 1 3]]


How to cast tensors to other data types with tf.cast

Some functions in TensorFlow and Keras requires specific data types as inputs, and we can do that with tf.cast. 

If you mostly have integers, you will probably find yourself casting from integer values to float values.

We can simply make a tensor with the datatype of float32. 

We can then cast this tensor to int, removing the comma and all decimals, while not rounding up or down.

In [ ]:
# Making a tensor
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)

#print(('Tensor with floats:\n{0}').format(tensor.numpy()))
#print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(tensor_as_int.numpy()))

print(('Tensor with floats:\n{0}').format(tensor))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(tensor_as_int))


Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [ ]:
tensor_as_float = tf.cast(tensor_as_int, tf.float32)
print(tensor_as_float)

tf.Tensor(
[[3. 2.]
 [5. 2.]
 [9. 5.]
 [1. 3.]], shape=(4, 2), dtype=float32)


# Linear Algebra Operations

Many algorithms or research needs these operations in order to implement algorithms and trying new things, e.g. making smaller changes in activation functions or optimizers. You will encounter some of these operations in my linear algebra series.

### Transpose tensor with tf.transpose
### Matrix Multiplication with tf.matmul
### Element-wise multiplication with tf.multiply
### Identity Matrix with tf.eye
### Determinant with tf.linalg.det
### Dot Product with tf.tensordot

## How to transpose a tensor with tf.transpose

Suppose we want to do linear algebra operations, then the tf.transpose function comes in handy. This produces A^T, i.e. it produces the transposed matrix of A.

In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(A))


The transposed matrix A:
[[3 1]
 [7 9]]


## How to do matrix multiplication with tf.matmul

Many algorithms requires matrix multiplication, and this is easy in TensorFlow with the tf.matmul function.

All we do here is define two matrices (one is a vector) and use the tf.matmul function to do matrix multiplication.

In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])
print(A)

# Some vector v
v = tf.constant([[5],
                 [2]])
print(v)

# Matrix multiplication of A and v
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(Av))


tf.Tensor(
[[3 7]
 [1 9]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5]
 [2]], shape=(2, 1), dtype=int32)
Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


## How to do element-wise multiplication with tf.multiply

Element-wise multiplication comes up in many instances, especially in optimizers. Reusing the tf.constants from before, such that we can compare the two, we simply use tf.multiply instead.

In [ ]:
# Element-wise multiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(Av))


Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


## How to make an identity matrix with tf.eye

In Linear Algebra, the identity matrix is simply a matrix with ones along the diagonal – and if you find the identity matrix of some matrix A, and multiply the identity matrix with A, the result will be the matrix A.

We simply define a tensor A, get the rows and columns and make an identity matrix.

In [ ]:
# Some Matrix A
A = tf.constant([[3, 7],
                 [1, 9],
                 [2, 5]])

# Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(rows, columns))

# Making identity matrix
A_identity = tf.eye(num_rows = 3,
                    num_columns = 3,
                    dtype = tf.int32)
#print(('\nThe identity matrix of A:\n{0}').format(A_identity.numpy()))
print('\nThe identity matrix of A:\n{0}'.format(A_identity))


Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## How to find the determinant with tf.linalg.det

The determinant can be used to solve linear equations or capturing how the area of how matrices changes.

We make a matrix A, then cast it to float32, because the tf.linalg.det does not take integers as input. Then we just find the determinant of A.

In [ ]:
# Reusing Matrix A
A = tf.constant([[3, 7],
                 [1, 9]])

# Determinant must be: half, float32, float64, complex64, complex128
# Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

# Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(det_A))


The determinant of A:
20.000001907348633


## How to find the dot product with tf.tensordot

Dotting one tensor onto another is perhaps one of the most common linear algebra operations. Hence, we should at least know how to find the dot product of two tenors in TensorFlow.

We just need to instantiate two constants, and then we can dot them together – note that in this instance, tf.tensordot is the same as tf.matmul, but there are differences outside the scope of this article.

In [ ]:
# Defining a 3x3 matrix
A = tf.constant([[32, 83, 5],
                 [17, 23, 10],
                 [75, 39, 52]])

# Defining another 3x3 matrix
B = tf.constant([[28, 57, 20],
                 [91, 10, 95],
                 [37, 13, 45]])

# Finding the dot product
#dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()
dot_AB = tf.tensordot(a=A, b=B, axes=1)

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(dot_AB))

# Which is the same as matrix multiplication in this instance (axes=1)
# Matrix multiplication of A and B
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(AB))


Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]

Matrix Multiplication of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


# In Tensorflow 2.0

## Calculating Gradients

In [ ]:
# TF 2 only

import math

def gelu(x):
    return 0.5*x*(1+tf.tanh(tf.sqrt(2/math.pi)*(x+0.044715*tf.pow(x, 3))))

def custom_func(x):
    return (2*x*x+3*x+10)

def get_gradient(x, activation_function):
    with tf.GradientTape() as gt:
        y = activation_function(x)

    gradient = gt.gradient(y, x).numpy()

    return gradient

x = tf.Variable(0.5)
gradient = get_gradient(x, gelu)

print('\n {0} is the gradient of GELU with x={1}'.format(gradient, x.numpy()))


x = tf.Variable(1.0)
gradient = get_gradient(x, custom_func)
print('\n {0} is the gradient of Custom Function with x={1}'.format(gradient, x.numpy()))



 0.8673698902130127 is the gradient of GELU with x=0.5

 7.0 is the gradient of Custom Function with x=1.0


## Functions In TensorFlow 2.0

TensorFlow Functions with **@tf.function** offers a significant speedup, because TensorFlow uses AutoGraph to convert functions to graphs, which in turn runs faster.

The annotation takes the normal Python syntax and converts it into a graph – and it has minimum side effects, which means we should always use it, especially when training and testing neural network models.

All that is done here is making an image and running it through conv_layer and conv_fn, then finding the difference.

In [ ]:
import timeit

conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
  return conv_layer(image)

image = tf.zeros([1, 200, 200, 100])

# warm up
conv_layer(image); conv_fn(image)

no_tf_fn = timeit.timeit(lambda: conv_layer(image), number=10)

with_tf_fn = timeit.timeit(lambda: conv_fn(image), number=10)

difference = no_tf_fn - with_tf_fn

print("Without tf.function: ", no_tf_fn)
print("With tf.function: ", with_tf_fn)
print("The difference: ", difference)

print("\nJust imagine when we have to do millions/billions of these calculations," \
      " then the difference will be HUGE!")
print("Difference times a billion: ", difference*1000000000)

Without tf.function:  0.005154347000029702
With tf.function:  0.0035128790000271692
The difference:  0.0016414680000025328

Just imagine when we have to do millions/billions of these calculations, then the difference will be HUGE!
Difference times a billion:  1641468.0000025327


## CPU/GPU Processing

In [ ]:
import time

cpu_slot = 0
gpu_slot = 0

# Using CPU at slot 0
with tf.device('/CPU:' + str(cpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    print(A)
    print('\n')
    
    print(tf.eye(2,2))

    # Printing how long it took with CPU
    end = time.time() - start
    print(end)



tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
0.0019001960754394531


In [ ]:
# Using the GPU at slot 0
with tf.device('/GPU:' + str(gpu_slot)):
    # Starting a timer
    start = time.time()

    # Doing operations on CPU
    A = tf.constant([[3, 2], [5, 2]])
    print(A)
    print('\n')
    print(tf.eye(2,2))

    # Printing how long it took with CPU
    end = time.time() - start
    print(end)


tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
0.004607439041137695
